{% set version = "3.0.3" %}

package:
  name: vswhere
  version: {{ version }}

source:
  url: https://github.com/microsoft/vswhere/releases/download/{{ version }}/vswhere.exe
  sha256: 261d281ce9c95c3e46900e67ace8c3518dd7b2596774f63c92e2bb1fbce71d4c

build:
  number: 0
  script: MOVE vswhere.exe %LIBRARY_BIN%\vswhere.exe
  skip: true  # [not win]

test:
  commands:
    - vswhere

about:
  home: https://github.com/microsoft/vswhere
  license: MIT
  license_file: LICENSE.txt
  summary: CLI tool to locate Visual Studio 2017 and newer installations
  description: |
    vswhere is designed to be a redistributable, single-file executable that
    can be used in build or deployment scripts to find where Visual Studio
    - or other products in the Visual Studio family - is located.

extra:
  recipe-maintainers:
    - wolfv
