context:
  version: 3.1.7

package:
  name: vswhere
  version: ${{ version }}

source:
  url: https://github.com/microsoft/vswhere/releases/download/${{ version }}/vswhere.exe
  sha256: c54f3b7c9164ea9a0db8641e81ecdda80c2664ef5a47c4191406f848cc07c662

build:
  number: 1
  # This is a noarch recipe because the binary provided can be run on `x86`, `x86_64` and `arm64`.
  # The maintainers of the project do not provide builds for `x86_64` or `arm64`. It also does 
  # not seem like thats going to happen: 
  # https://github.com/microsoft/vswhere/issues/306
  noarch: generic
  script: mkdir -p $PREFIX/Library/bin/; mv vswhere.exe $_

requirements:
  run:
    - __win
  
tests:
  - package_contents:
      files: 
        - Library/bin/vswhere.exe

about:
  homepage: https://github.com/microsoft/vswhere
  repository: https://github.com/microsoft/vswhere
  license: MIT
  license_file: LICENSE.txt
  summary: CLI tool to locate Visual Studio 2017 and newer installations
  description: |
    vswhere is designed to be a redistributable, single-file executable that
    can be used in build or deployment scripts to find where Visual Studio
    - or other products in the Visual Studio family - is located.

extra:
  recipe-maintainers:
    - wolfv
    - baszalmstra
