noarch_platforms: win_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_install_tool: pixi
conda_build_tool: rattler-build
test: native_and_emulated
